### ISSUE TITLE
Error: Start Sylk push server

### ISSUE THREAD

**Issue by hrg92** [AGProjects/sylk-pushserver#10]
I'm starting the sylk push server service but it doesn't work for me

I am running the following command at /opt/sylk_pushserver-1.0.1
./sylk-pushserver --config_dir /etc/sylk_pushserver-1.0.1/config/

and it shows me the following error

INFO:root:2022-11-16 04:35:18.492767 Starting Sylk Pushserver...
ERROR:to_file:2022-11-16 04:35:18.496601 Can not start: applications.ini config file not found
Can not start: applications.ini config file not found

What should I do to lift the service?

**Comment by tijmenNL** [comment]
Does the directory exist? 

What is the output of `ls /etc/sylk_pushserver-1.0.1/config/`?

**Comment by hrg92** [comment]
Sorry, the correct path is as follows:

/opt/sylk_pushserver-1.0.1/config/

Inside config/ are the following folders.
applications (folders)
applications.ini.sample (archive)
general.ini.sample (archive)
opensips.cfg (archive)
pns (folder)

**Comment by tijmenNL** [comment]
Well see: https://github.com/AGProjects/sylk-pushserver#configuration

You need to configure the push server before you can use it. You can start by renaming the *sample files and adjust them to your needs.

**Comment by hrg92** [comment]
Ok thanks

To use the sylk push server service, I must have the sylkserver service active. ?

When activating the sylkserver service it gives me the following error

![image](https://user-images.githubusercontent.com/97411986/202491643-88241880-295b-41d1-b14a-16d1e59e49ca.png)

**Comment by tijmenNL** [comment]
You don't need Sylkserver for the push server to work.

Sylk Pushserver is designed to act as a central dispatcher for mobile push notifications. It accepts HTTP POST requests over the API and sends out a push request to Apple Push Notifications or Firebase FCM servers. Anything that can do a HTTP POST can interface with it. See https://github.com/AGProjects/sylk-pushserver/tree/master/scripts for example scripts to send a push notification.

Sylkserver can use this API to send push requests for messages and incoming calls when the webrtcgateway application is being used by a compatible mobile client.

If you have an issue with Sylkserver, this is not place to discuss it.

**Comment by hrg92** [comment]
ok thanks.

What we want is to do the following:

We want to use sylkserver as a proxy and when there is an incoming call the sylk -push server after the android app.

Can it be done this way?

**Comment by hrg92** [comment]
ok thanks.

What we want is to do the following:

We want to use sylkserver as a proxy and when there is an incoming call the sylk -push server after the android app.

Can it be done this way?

**Comment by tijmenNL** [comment]
If you have a particular question that is not covered by the documentation, you can use the SIP Beyond VoIP mailing list for Sylkserver and Sylk-Pushserver: https://lists.ag-projects.com/mailman/listinfo/sipbeyondvoip
