### ISSUE TITLE
Error Sylk push server 

### ISSUE THREAD

**Issue by hrg92** [AGProjects/sylk-pushserver#11]
Hello

Install debian buster to install sylkpush server as you recommend

I ran apt update and apt get install sylk push server

when running the service it gives me this error

![image](https://user-images.githubusercontent.com/97411986/203827455-a8419d28-5ac9-458a-aa27-4b24b6e1adcd.png)

**Comment by tijmenNL** [comment]
Please provide a meaningful log where it shows what fails. (syslog/journalctl)

**Comment by hrg92** [comment]
this record is functional

![image](https://user-images.githubusercontent.com/97411986/203838701-6fa4163d-e637-457b-8e04-88323f3598ff.png)

**Comment by tijmenNL** [comment]
OK. This is logging of systemd where it shows that it can't start the service, just like your previous screen shot. It does not show why it does not start.  You need to obtain the logging of sylk-pushserver. 

Did you configure the push server, or you just did `apt-get install sylk-pushserver`?

**Comment by hrg92** [comment]
just run apt-get install sylk-pushserver

**Comment by tijmenNL** [comment]
I just did the same. Then I retrieved the log:
```
journalctl -u sylk-pushserver
systemd[1]: Started Sylk Push Notifications server.
sylk-pushserver[14343]: INFO:root:2022-11-24 19:45:25.212522 Starting Sylk Pushserver...
sylk-pushserver[14343]: ERROR:to_file:2022-11-24 19:45:25.212896 Can not start: applications.ini config file not found
sylk-pushserver[14343]: Can not start: applications.ini config file not found
```
It tells you exactly why it does not work. It is the same reason as your earlier attempt. See https://github.com/AGProjects/sylk-pushserver/issues/10#issuecomment-1317268386
