### ISSUE TITLE
Push-Sylkserver Not Pushing Notifications after upgrade

### ISSUE THREAD

**Issue by hasanr68** [AGProjects/sylk-pushserver#13]
Related to https://github.com/AGProjects/sylk-pushserver/issues/12#issue-1584165378

I am getting the following error when notifications need to be sent:

ERROR    [asyncio] Unhandled exception in event loop#012ERROR    [asyncio] Traceback (most recent call last):#012ERROR    [asyncio]   File "uvloop/handles/streamserver.pyx", line 135, in uvloop.loop.__uv_streamserver_on_listen#012ERROR    [asyncio]   File "uvloop/handles/streamserver.pyx", line 57, in uvloop.loop.UVStreamServer._on_listen#012ERROR    [asyncio]   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 80, in __init__#012ERROR    [asyncio]     self.parser = httptools.HttpRequestParser(self)#012ERROR    [asyncio] AttributeError: module 'httptools' has no attribute 'HttpRequestParser'

**Comment by tijmenNL** [comment]
Check what this outputs `dpkg --list | grep python3-httptools`.

If it is empty install python3-httptools

**Comment by hasanr68** [comment]
Was empty, now:
ii  python3-httptools                   0.0.11-1                              amd64        framework independent HTTP protocol utils (Python3 version)

**Comment by hasanr68** [comment]
Everything good! Thx a lot.

**Comment by tijmenNL** [comment]
Ok, thanks for confirming
