### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer and BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by zjacky0992** [AGProjects/sylk-pushserver#6]
The push server works great! Thank you! When we did the tests, we found the connection between the push server and the apns was reset every several hours. No push notification can't be resent after that unless we restart the server. Here are the logs:

Sep 16 17:05:33 sipserver sylk-pushserver[28555]: Traceback (most recent call last):
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     result = await app(self.scope, self.receive, self.send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return await self.app(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/fastapi/applications.py", line 149, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await super().__call__(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.middleware_stack(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     raise exc from None
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.app(scope, receive, _send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     raise exc from None
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.app(scope, receive, sender)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await route.handle(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.app(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     response = await func(request)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/fastapi/routing.py", line 148, in app
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     dependant=dependant, values=values, is_coroutine=is_coroutine
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/fastapi/routing.py", line 101, in run_endpoint_function
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return await dependant.call(**values)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/api/routes/push.py", line 62, in push_requests
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     results = handle_request(wp_request, request_id=request_id)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/resources/notification.py", line 19, in handle_request
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     results = push_notification.send_notification()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/resources/notification.py", line 92, in send_notification
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     register=register)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/pns/apple.py", line 265, in __init__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self.results = self.send_notification()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/pns/apple.py", line 305, in send_notification
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     response = self.connection.get_response()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/connection.py", line 312, in get_response
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return HTTP20Response(stream.getheaders(), stream)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/stream.py", line 230, in getheaders
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self._recv_cb(stream_id=self.stream_id)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/connection.py", line 771, in _recv_cb
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self._single_read()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/connection.py", line 665, in _single_read
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self._sock.fill()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/common/bufsocket.py", line 167, in fill
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     count = self._sck.recv_into(self._buffer_view[self._buffer_end:])
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return self.read(nbytes, buffer)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3.7/ssl.py", line 911, in read
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return self._sslobj.read(len, buffer)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]: ConnectionResetError: [Errno 104] Connection reset by peer
Sep 16 17:05:33 sipserver sylk-pushserver[28555]: ERROR:uvicorn.error:Exception in ASGI application
Sep 16 17:05:33 sipserver sylk-pushserver[28555]: Traceback (most recent call last):
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     result = await app(self.scope, self.receive, self.send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return await self.app(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/fastapi/applications.py", line 149, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await super().__call__(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.middleware_stack(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     raise exc from None
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.app(scope, receive, _send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     raise exc from None
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.app(scope, receive, sender)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await route.handle(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.app(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     response = await func(request)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/fastapi/routing.py", line 148, in app
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     dependant=dependant, values=values, is_coroutine=is_coroutine
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/fastapi/routing.py", line 101, in run_endpoint_function
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return await dependant.call(**values)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/api/routes/push.py", line 62, in push_requests
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     results = handle_request(wp_request, request_id=request_id)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/resources/notification.py", line 19, in handle_request
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     results = push_notification.send_notification()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/resources/notification.py", line 92, in send_notification
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     register=register)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/pns/apple.py", line 265, in __init__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self.results = self.send_notification()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/pns/apple.py", line 305, in send_notification
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     response = self.connection.get_response()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/connection.py", line 312, in get_response
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return HTTP20Response(stream.getheaders(), stream)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/stream.py", line 230, in getheaders
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self._recv_cb(stream_id=self.stream_id)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/connection.py", line 771, in _recv_cb
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self._single_read()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/connection.py", line 665, in _single_read
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self._sock.fill()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/common/bufsocket.py", line 167, in fill
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     count = self._sck.recv_into(self._buffer_view[self._buffer_end:])
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return self.read(nbytes, buffer)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3.7/ssl.py", line 911, in read
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return self._sslobj.read(len, buffer)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]: ConnectionResetError: [Errno 104] Connection reset by peer

The push server tried to send several times, but got the error BrokenPipeError: [Errno 32] Broken pipe. Here are the logs:

Sep 16 17:05:33 sipserver sylk-pushserver[28555]: ERROR:uvicorn.error:Exception in ASGI application
Sep 16 17:05:33 sipserver sylk-pushserver[28555]: Traceback (most recent call last):
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     result = await app(self.scope, self.receive, self.send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return await self.app(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/fastapi/applications.py", line 149, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await super().__call__(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.middleware_stack(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     raise exc from None
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.app(scope, receive, _send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     raise exc from None
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.app(scope, receive, sender)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await route.handle(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     await self.app(scope, receive, send)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     response = await func(request)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/fastapi/routing.py", line 148, in app
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     dependant=dependant, values=values, is_coroutine=is_coroutine
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/fastapi/routing.py", line 101, in run_endpoint_function
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return await dependant.call(**values)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/api/routes/push.py", line 62, in push_requests
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     results = handle_request(wp_request, request_id=request_id)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/resources/notification.py", line 19, in handle_request
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     results = push_notification.send_notification()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/resources/notification.py", line 92, in send_notification
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     register=register)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/pns/apple.py", line 265, in __init__
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self.results = self.send_notification()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/pushserver/pns/apple.py", line 303, in send_notification
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self.headers)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/connection.py", line 281, in request
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self.endheaders(message_body=body, final=True, stream_id=stream_id)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/connection.py", line 555, in endheaders
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     stream.send_headers(headers_only)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/stream.py", line 99, in send_headers
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self._send_outstanding_data()
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/connection.py", line 466, in _send_outstanding_data
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self._send_cb(data, tolerate_peer_gone=tolerate_peer_gone)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3/dist-packages/sylk-pushserver/lib/python3.7/site-packages/hyper/http20/connection.py", line 622, in _send_cb
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     self._sock.sendall(data)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3.7/ssl.py", line 1015, in sendall
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     v = self.send(byte_view[count:])
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:   File "/usr/lib/python3.7/ssl.py", line 984, in send
Sep 16 17:05:33 sipserver sylk-pushserver[28555]:     return self._sslobj.write(data)
Sep 16 17:05:33 sipserver sylk-pushserver[28555]: BrokenPipeError: [Errno 32] Broken pipe

**Comment by tijmenNL** [comment]
This should be fixed now with the switch to httpx instead of hyper 7348919
