### ISSUE TITLE
iPhone - audio call notification appears as video call.

### ISSUE THREAD

**Issue by hasanr68** [AGProjects/sylk-pushserver#8]
Thought I'd point out one more thing I noticed when making audio calls.

App active - call appears as audio call.
Phone active - call appears as audio call.
Phone locked - call appears as video call.

Unsure why that is happening. Let me know if you need more details.

**Comment by tijmenNL** [comment]
From the perspective of the pushserver we don't know anything about the state of the phone. We just send out the notification to apple. This is the same if the phone is locked, active or the app is active. 

You need to check with the app maker why this is happening.

**Comment by hasanr68** [comment]
Thanks.
